name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'


permissions:
  contents: read

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@8358ee0e2e8afe63c2fb8253d1d52085811ab1e5 # v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
